site_name: Dongyun Han
pages:
  - Home: index.md
  - Intorduction: introduction.md
  - Visualanalytics: visualanalytics.md
  - How To: how_to.md
  - big5: big5.md
  - svg: svg.md
extra_css: [big5.css]
